fix(Tactic/Linter/TextBased): don't suggest `--fix` when it's already used (#44579)
`lake exe lint-style --fix` says
```
error: found 1 new style error(s)! Try `lake exe lint-style --fix` to apply automatic fixes.
```
which is confusing, since we already passed `--fix`. So now it says
```
info: found and fixed 1 new style error(s)!
```